name: Build & test
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            matrix:
                python-version:
                    - 3.9
        services:
            mysql:
                image: mariadb:latest
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Initialize MariaDB
                run: |
                    mysqladmin --host=127.0.0.1 ping
            -
                name: 'Set up Python ${{ matrix.python-version }}'
                uses: actions/setup-python@v2
                with:
                    python-version: '${{ matrix.python-version }}'
            -
                name: Install build dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install poetry tox pre-commit
            -
                name: Test with tox
                run: |
                    tox -v
            -
                name: Run coveralls
                # the || true is because coveralls returns a nonzero exit code on warnings, etc.
                run: |
                    coveralls || true
